# minibatch related
batch-size: 4
maxlen-in: 2000
maxlen-out: 150

# optimization related
criterion: loss
early-stop-criterion: "validation/main/loss"
sortagrad: 0
opt: noam
noam-lr: 10.0
noam-adim: 256
optimizer-warmup-steps: 25000
epochs: 40
patience: 5
accum-grad: 2
grad-clip: 5.0

# network architecture
## general
custom-enc-positional-encoding-type: rel_pos
custom-enc-self-attn-type: rel_self_attn
custom-enc-pw-activation-type: swish
## encoder related
etype: custom
custom-enc-input-layer: vgg2l
enc-block-arch:
        - type: conformer
          d_hidden: 640
          d_ff: 1024
          heads: 8
          macaron_style: True
          use_conv_mod: True
          conv_mod_kernel: 7
          dropout-rate: 0.3
          att-dropout-rate: 0.3
enc-block-repeat: 6
## decoder related
dtype: lstm
dlayers: 1
dec-embed-dim: 1024
dunits: 768
dropout-rate-embed-decoder: 0.2
dropout-rate-decoder: 0.1
## joint network related
joint-dim: 256

# transducer related
model-module: "espnet.nets.pytorch_backend.e2e_asr_transducer:E2E"
